---   # parameter configure
lgMmin:
  free: true
  default: 14
  prior: [10, 17]
sig_lgM:
  free: true
  default: 1
  prior: [1e-3, 3]
Amp:
  free: true
  default: 0.7
  prior: [0, 1]

lgM0:
  free: false
  default: 50         # set to a crazy number, so that Ns is always zero.
  # prior: [11, 16]
lgM1p:
  free: false
  default: 12
  prior: [10.5, 16]
alpha:
  free: false
  default: 1
  prior: [0.1, 5]

---   # general configure
Nwalkers: 40          # walkers you use
Nstep: 8000           # steps to go
Nburnin: 800          # burnin
Npro: 40              # process to use

auto_range: [6, 23]   # range for fitting auto corr. the default is the whole range.
cross_range: [0, 13]  # range for fitting cross corr. the default is the whole range.
backend_file: backend_m.bin # backend file
numpy_file: np_m
# wp_table_path: ../wp_table_small
wp_table_path: ../wp_table
signal_path: ../signal_nc